version: "3"
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./public_html/:/var/www/
      - ./nginx.conf.d/:/etc/nginx/conf.d/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: webcdr_Demo
    working_dir: /htmlmasondemo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
